runtime: nodejs22
env: standard

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6
  target_throughput_utilization: 0.6
  max_concurrent_requests: 80
  min_pending_latency: 30ms
  max_pending_latency: 100ms

env_variables:
  PLATFORM: "App Engine"
  DEPLOYMENT_TYPE: "Google App Engine"
  NODE_ENV: "production"